# Site settings
title: Of Data Monsters
header-img: img/home-bg.jpg
email: kaleajinkya@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://ajkl.github.io"
twitter_username: ajinkyakale
github_username: ajkl
disqus: ajinkyakale
google_analytics: UA-57080517-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
